services:
  mysql:
    container_name: mysql-server
    image: mysql:8.4.7
    secrets:
      - mysql_root_password
      - mysql_user_password
    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "3306:3306"
    volumes:
      # - /var/lib/mysql                # Anonymous
      - mysql-data:/var/lib/mysql       # Named
      # - ./mysql-data:/var/lib/mysql   # Bind mount
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u $MYSQL_USER -p$(cat /run/secrets/mysql_root_password) -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - my-net
#    network_mode: host

  users-ws:
    container_name: users-ws
    image: 4594400/users-ws-public:2.0.1
    build:
      context: "./Users"
      dockerfile: "Dockerfile-multi-stage"
      tags:
        - users-ws:latest
        - users-ws:2.0.1
    ports:
      - "8082:8082"
    secrets:
      - spring.datasource.password
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE_ACTIVE}
      SPRING_CONFIG_IMPORT: "configtree:/run/secrets/"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-net
#    network_mode: host

volumes:
  mysql-data:

networks:
  my-net:
    name: my-net
    driver: bridge

secrets:
  spring.datasource.password:
    file: ./secrets/mysql_user_password
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password
